name: Don't leave me behind

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Billie Jean, baby please, he's a criminal
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Get version
        id: get_version
        shell: bash
        run: echo "version=$(node -p "require('./package.json').version")" >> "$GITHUB_OUTPUT"

      - name: Set up Node.js
        uses: actions/setup-node@main
        with:
          node-version: latest

      - name: Set up pnpm
        uses: pnpm/action-setup@master

      - name: Build!
        shell: bash
        run: |
          pnpm install
          npx --yes esbuild --minify --allow-overwrite --legal-comments=none server.js --outfile=./server.js
          npx --yes esbuild --minify --allow-overwrite --legal-comments=none resources/index.js --outfile=resources/index.js
          npx --yes esbuild --minify --allow-overwrite --legal-comments=none resources/style.css --outfile=resources/style.css
          curl -LO https://raw.githubusercontent.com/moaeiou/moaeiou/refs/heads/main/.github/workflows/format.js
          node format.js index.html ./index.html
          node format.js server.js ./server.js
          node format.js resources/index.js resources/index.js
          node format.js resources/style.css resources/style.css
          tar -cvf contento24.tar.zst --zstd server.js index.html package.json pnpm-lock.yaml pnpm-workspace.yaml LICENSE resources/ node_modules/

      - name: Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: V${{ steps.get_version.outputs.version }}
          files: contento24.tar.zst
          body: |
            # 📝 Release Note
            - Fixes and improvements
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send to mirror
        uses: moaeiou/moaeiou/actions/rsync@main
        with:
          local: contento24.tar.zst
          remote: /var/www/html/
